name: Update Chess Ratings

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Google Credentials File
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | base64 --decode > google-credentials.json
        shell: bash

      - name: Run update script
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python update_sheets_tracker.py